<../../mkconfig

# Lua Test Suite

TARG=\
	test_disparser\
	test_functioncaller\

MODULES=\
	test_disparser.b\
	test_functioncaller.b\

SYSMODULES=\
	sys.m\
	draw.m\
	luavm.m\
	luadisparser.m\
	limbocaller.m\

DISBIN=$ROOT/dis/lib

<$ROOT/mkfiles/mkdis
